### ISSUE TITLE
Questions for fg22 tags without external devices. 

### ISSUE THREAD

**Issue by men9xuan** [OpenEPaperLink/Tag_FW_EFR32xG22#1]
Hi stevew817,

Thanks for the great work. 
I'm working on compiling firmware for a SES price tag that has a 256KB FG22 chip with no external flash. I noticed that the DISPLAYDATA tag also uses the FG22 chip, so I'm using that as a reference. However, I have a few questions:

1. Is the bootloader compatible between BG22 and FG22 devices?
2. Do I need an external flash to flash this custom firmware?
3. Where is `USERDATA_BASE` defined? I think it's from the GSDK, but I'm not sure.
4. I can see that the DISPLAYDATA tag firmware is generated, but the `oepl_efr32_hwtypes` file doesn't seem to have any hardware specific pin definitions. So where are the specific GPIO definitions that are passed to the application?

Thanks for your help.

**Comment by atc1441** [comment]
Hey @men9xuan
That company is not suoported or to be discussed in the OpenEpaperLink Project.

**Comment by men9xuan** [comment]
Uhhh sorry I did not know that . @atc1441  Can you please delete this issue? I will try to reword the question without naming the company

**Comment by atc1441** [comment]
I can only kindly ask to stop working on that hardware
