### ISSUE TITLE
Inconsistent resolution for solum 2.2 tag. 

### ISSUE THREAD

**Issue by krikkirk** [OpenEPaperLink/Tag_FW_EFR32xG22#4]
Hi Steven, 

I have some issue with a solum 2.2 bwr epl. I believe the resolution should be 250x128 from its `USERDATA_BASE` however, in OEPL it was identified as 296x160.
![image](https://github.com/user-attachments/assets/3b7c77f9-de4b-4126-a8bd-587593830b2b)
The display works fine for the UI: Splash Screen, UI: AP Found, but for the other contents it is glitched and unreadable. Can you please look at this issue?
ps: I edited the value at `0fe00016` from `51` to `41` to get the tag recognized. 

Thanks 
[userdata2.2.txt](https://github.com/user-attachments/files/16475366/userdata2.2.txt)

**Comment by krikkirk** [comment]
I think the problem is from the tagtypes file https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/resources/tagtypes/31.json #

**Comment by stevew817** [comment]
Huh. This should probably be a shared ticket between the firmware and the main OEPL tagtype database, as it sounds like there needs to be a new tagtype for this. The firmware detects the actual resolution correctly from userdata, as evidenced by the working splashscreen (which is dynamically generated by the firmware), but doesn't use a tagtype with a correct resolution for the AP to generate images with the correct resolution.

**Comment by krikkirk** [comment]
Yeah. I think I got everything needed to make the "lite" m3 2.2 working locally and I would like to create a PR with support for it.
I am having some hard time determining the correct value for the new tag
`#define SOLUM_M3_BWR_22_LITE 0x47`
`#define STYPE_SIZE_022_LITE 0x51` 
in the following files. However, it seems that the constants in the two files are not always mapped to a json file under `resources\tagtypes` and vice versa. 
For example, there is no 0x44 in the following two files but there is [44.json](https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/resources/tagtypes/44.json)
https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/oepl-definitions.h
https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/tag_types.h
On the contrary, there are `0x3A ` `0x3B ` `0x3C ` `0x3D ` in the above two files but no corresponding json under `resources\tagtypes`.
 Is there some other mapping that I am missing?
